### ISSUE TITLE
请问 contain_el 是指什么？

### ISSUE THREAD

**Issue by kiwiflydream** [Liugq5713/watermarkToDiv#1]
是选择器的表达式吗？ #app  .app 这种吗？

**Comment by Liugq5713** [comment]
> 是选择器的表达式吗？ #app .app 这种吗？

sorry，回复晚了，因为水印是通过css，对一个元素的background添加的，那么contain_el就是指定这个元素

**Comment by kiwiflydream** [comment]
好的，谢谢
