### ISSUE TITLE
现在这个版本直接使用会报错

### ISSUE THREAD

**Issue by jihainan** [Liugq5713/watermarkToDiv#2]
`vue.runtime.esm.js?2b0e:1888 DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`

**Comment by Liugq5713** [comment]
> `vue.runtime.esm.js?2b0e:1888 DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`

不可能的，demo没什么问题，如果你想直接用在vue中，那么我之前写了一个vue版本的组件你可以直接复制  https://github.com/Liugq5713/components/blob/master/src/components/WatermarkToDiv/WatermarkToDiv.vue
ps： 回复晚了，我很抱歉
